# Generated by Django 3.1.7 on 2021-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210415_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click The Link Above To Read BlogPost.....', max_length=255),
        ),
    ]
