# Generated by Django 3.1.7 on 2021-04-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
