# Generated by Django 3.1.7 on 2021-04-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_auto_20210417_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
